### ISSUE TITLE
Написать .ino скрипт для калибровки серво

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#1]
Написать скрипт для калибровки позиций сервоприводов в шеститочечной ячейке. Управление через Serial. Детали в файле по [ссылке](https://github.com/zuevval/braille/blob/calibrate/arduino/alexey_task.txt). Просьба коммитить в ветку calibrate

**Comment by aalksii** [comment]
Completed.

**Comment by zuevval** [comment]
> 
> 
> Completed.

Протестировал поверхностно. Нашёл опечатку в Servo_setInside и поставил свои startPos, Steps ([вот в этом коммите](https://github.com/zuevval/braille/commit/d732f91e34cdf71a433634fb90477fc48d26f667)) <br>
Мне кажется или при изменении s\<digit\>.on+\<digit\> не изменяется позиция серво, а только цифра? В любом случае, после этой команды серво должен прийти в новое положение (даже если был в позиции off)

**Comment by zuevval** [comment]
> Completed.

Но ты молодец

**Comment by aalksii** [comment]
> Мне кажется или при изменении s<digit>.on+<digit> не изменяется позиция серво, а только цифра? В любом случае, после этой команды серво должен прийти в новое положение (даже если был в позиции off)

Действительно, в setInside была ошибка. 
[Добавил](https://github.com/zuevval/braille/commit/d03158ffee23fbb9b6f8d6744cb72664a277f45f) изменение позиции серво при внесении правок в калибровочные массивы.

**Comment by zuevval** [comment]
> 
> 
> > Мне кажется или при изменении s.on+ не изменяется позиция серво, а только цифра? В любом случае, после этой команды серво должен прийти в новое положение (даже если был в позиции off)
> 
> Действительно, в setInside была ошибка.
> [Добавил](https://github.com/zuevval/braille/commit/d03158ffee23fbb9b6f8d6744cb72664a277f45f) изменение позиции серво при внесении правок в калибровочные массивы.

Всё исправлено. Сейчас откалибрую моторы, волью ветку в master и закрою issue

**Comment by zuevval** [comment]
Всё в порядке. Влил в master
