### ISSUE TITLE
Улучшение печати строки в Arduino

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#16]
Основа - скетч [print_letters](https://github.com/zuevval/braille/tree/master/arduino/print_letters) (который, кстати, был составлен из Calibrating.ino) и скетч joystick (на текущий момент он есть в ветке joystick) <br>
**Составить .ino-скетч**, который, используя функцию printString из [print_letters](https://github.com/zuevval/braille/tree/master/arduino/print_letters),
1. Выводит принятый по Serial текст в ячейку Брайля
2. По окончании печати строки выводит + в Serial
3. Реагирует на нажатия джойстика (хотя бы в то время, пока не выводит текст). Здесь пользоваться скетчем joystick из ветки Joystick

**Comment by zhenyatos** [comment]
Done.
