### ISSUE TITLE
Обработка нажатий джойстика на Python

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#18]
В Serial `ser` в произвольном порядке поступают буквы u (up), l (left), r (right), d (down), s (sound), m (mute). <br>
Написать функцию `listen_joystick(ser)`, возвращающую строку или первую букву строки (как удобнее, всё равно), пришедшую черезе`ser`. Пока что это могут быть только u, l, d, r или знак +

**Comment by aalksii** [comment]
Закоммитил в ветку issue18.

**Comment by aalksii** [comment]
Смерджино с мастер-веткой.
