### ISSUE TITLE
Сделать код Arduino асинхронным

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#19]
В функции `printString()`  в файле [print_string.ino](https://github.com/zuevval/braille/tree/master/arduino/print_letters) (в вызываемых этой функцией функциях) заменить `delay` асинхронным кодом для обработки нажатий джойстика в любой момент, даже во время воспроизведения. <hr>
Побочный Issue. Сделать, если успеваем.

**Comment by aalksii** [comment]
Нужны тесты с джойстиком. Ветка программы с асинхронным кодом - issue19 (нерабочая версия, а в master - рабочая).

**Comment by zhenyatos** [comment]
Замена if на while.
