### ISSUE TITLE
Подключение динамика и связь с кнопкой.

### ISSUE THREAD

**Issue by zhenyatos** [zuevval/braille#26]
- [x] Подключить нажимную кнопку и динамик к Ардуино.
**Написать программу, требуется:**
- [x] Подача сигнала динамика при нажатии на джойстик, при условии что кнопка отпущена
- [x] Подача сообщения о перемене состояния кнопки в Serial (s - sound, m - mute)

**Comment by zuevval** [comment]
Создать себе отдельную ветку sound_arduino
