### ISSUE TITLE
Очередь запросов в serial

### ISSUE THREAD

**Issue by aalksii** [zuevval/braille#31]
Необходимо исправить баг с очередью запросов: когда ардуино говорит, т. е. не слушает, каждая команда джойстика добавляется в очередь. Потом ардуино выполняет по очеерди все эти запросы. Одно из решений проблемы: когда ардуино слушает, отправлять с помощью python в serial '?', тогда ардуино будет понимать, когда нужно отправлять 'ruld'.

**Comment by aalksii** [comment]
Относится к issue 30.

**Comment by aalksii** [comment]
Еще как вариант: стирать serial.

**Comment by aalksii** [comment]
Просьба коммитить в отдельную ветку, не мастер.

**Comment by zhenyatos** [comment]
Ветка issue-31.

**Comment by zhenyatos** [comment]
Done.
