### ISSUE TITLE
Появление букв на дисплее Брайля

### ISSUE THREAD

**Issue by aalksii** [zuevval/braille#35]
Сделать корректную работу последовательного вывода слогов, к примеру, аб и ба. Проблема в том, что эти буквы имеют одинаковые точки, поэтому при переходе, чтобы убрать точки перед новой буквой, приходится использовать:
```
    less4 = LessonStep('audio/lesson1v2/l1s4.wav', 'аб', comment='АБ')
    less5 = LessonStep('', ' ', comment='')
    less6 = LessonStep('audio/lesson1v2/l1s5.wav', 'ба', comment='БА')
```
Нужно убрать среднюю строку, ибо повтор урока не работает как надо.

**Comment by zuevval** [comment]
done (good job)
