### ISSUE TITLE
Добавить цифры

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#40]
- [x] В файле serial_hex добавить обработку цифр (кроме букв)
- [x] вывести в консоль текущее время (создать функцию curr_time()) с разделителем - пробелом
Назначение: приложение - часы

**Comment by aalksii** [comment]
Перед числом ставится цифровой знак.
![image](https://user-images.githubusercontent.com/34196081/52415510-31f66c80-2af8-11e9-8c36-f5a0692cbc9a.png)
