### ISSUE TITLE
Синтез речи

### ISSUE THREAD

**Issue by aalksii** [zuevval/braille#47]
Перевести всю систему на синтез речи (отпадет необходимость в след. приложениях записывать шаблоны) <br>
На текущий момент логично поступить так:
- [x] написать функцию для синтеза фразы с помощью `RHVoice`+`pyttsx3`/`RHVoiceWrapper`/чем-то ещё, что может работать с Windows
- [x] Сделать воспроизведение синтезированных фраз асинхронным - средствами самой библиотеки, либо с помощью [кода Макара](https://github.com/zuevval/braille/issues/75#issuecomment-478346504), либо как-то ещё (в крайнем случае записывать в файл и воспроизводить с `playSoundByFilename`)
- [x] В качестве теста перевести на синтез заметки
- [x] Озвучивать текст заметки параллельно с выводом символов Брайля

После этого можно будет судить, годится ли синтез для всей системы.

**Comment by zuevval** [comment]
Это представляется сложным, если хочется работать офлайн. <br>
[Статья на Хабре об онлайн-синтезе](https://habr.com/ru/sandbox/46676/) <br>
[Ответ со StackOverflow на русском об офлайн-синтезе](https://ru.stackoverflow.com/questions/844927/offline-%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7-%D1%80%D0%B5%D1%87%D0%B8) <br>
Вообще я спрошу у Нины Константиновны и прочих. Может, им приятно слышать не синтезатор, а запись. Фразы же всё равно надо придумывать, записать их, кажется, не так и сложно.

**Comment by aalksii** [comment]
Это может пригодиться для озвучки записей в блокноте

**Comment by zuevval** [comment]
Вновь интересно (особенно в связи со всё растущим числом аудиозаписей)

**Comment by zuevval** [comment]
Windows: найдено перспективное решение - `pyttsx`+`RHVoice` (это, по всей видимости, можно и на Linux) либо `pyttsx` + `Microsoft Elena` (для Windows 10)

[pyttsx tutorial](https://www.devdungeon.com/content/text-speech-python-pyttsx3#change_voice_language)
[download RHVoice](https://nvda.ru/links/rhvoice-0.7.1-sapi5.php)
[RHVoice - все версии, в т. ч. портативная](https://nvda.ru/sintezator-rhvoice#komplekt-rhvoice-v071-sapi5-razdelnye-komponenty)

**Comment by zuevval** [comment]
Реализовано нормально, работает.

**Но при запуске в дебаггере выходят ошибки из запущенных потоков**. Это надо когда-нибудь исправить.
