### ISSUE TITLE
Подумать над более рациональным выводом буквы

### ISSUE THREAD

**Issue by aalksii** [zuevval/braille#48]
Варианты: барабаны, диск (включая набор).

**Comment by zuevval** [comment]
Очень расплывчато, поэтому не годится как issue. Записал в "идеи по железу" на вкладке проекта. <br>
 [Вот такой есть барабан](http://www.ecs.umass.edu/ece/sdp/sdp16/team15/sdp16.my-free.website/index.html); диск вряд ли будет обеспечивать удобное чтение и ввод. Issue закрываю
