### ISSUE TITLE
Склонировать репозиторий (всем!)

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#51]
Каждому просьба:
1. git clone https://github.com/zuevval/braille.git
1. Проверить, что всё в порядке (попробовать запустить main.py и убедиться, что до Serial-ошибок нет ошибок; открыть любую из ppt-презентаций, чтобы убедиться, что работает LFS).
1. Написать в комментариях под issue о том, что всё работает
1. Кому-то хорошо бы на всякий случай сделать fork

**Comment by zuevval** [comment]
У меня всё в порядке.

**Comment by mualal** [comment]
Всё работает. Только не воспроизводит аудио с расширением .wav, но воспроизводит с расширением .WAV. <bf>
С расширением .WAV воспроизводит как в плеере, так и из файла audio.py при вызове функции playSoundByFilename

**Comment by zuevval** [comment]
С аудио разобрались - это, видимо, была проблема с Git LFS
