### ISSUE TITLE
Сделать новую сборку

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#54]
- [x] Создать новую ветку “feature/parts”
- [x] В папке parts/solidworks2 создать модель PWM Shield (главное - обозначить габариты).
- [x] показать Валере (хорошо бы во вторник-среду)
- [x] разместить в одной сборке .asm шилд, Ардуино, ячейку, уголки (arduino и уголки в папке parts/solidworks/)
- [x] с помощью Валеры из детали parts/solidworks/deck-lower создать одноимённую в solidworks2. Скорректировать размеры и сделать отверстия под винты.

**Comment by zuevval** [comment]
Ветка уже сделана Валерой, т. к. надо было добавить маленькое изменение в модель

**Comment by IvanBegun** [comment]
Добавил модель PWM Shield
