### ISSUE TITLE
Ввод символов с помощью кнопок

### ISSUE THREAD

**Issue by aalksii** [zuevval/braille#59]
- [x] В отсутствие подключения к компьютеру выводить символ Брайля по нажатию комбинации клавиш.

- [x] Нарисовать принципиальную схему сборки кнопок (пока 6, в дальнейшем прибавим пробел).

- [x] * Проверка подключения к ПК (выводить в сериал символ при подключении и откл.) - сделать при необходимости.

- [x] Вывод введенного символа в сериал.

- [x] Расширить функцию listen_joystick до просто listen, обрабатывающую и нажатия клавиш.

- [ ] То же - в меню приложений, но внутри приложений не надо.

- [ ] Проигрывать аудио с названием буквы (в главном меню).

**Comment by aalksii** [comment]
Клавиатура:
![braille_keyboard](https://user-images.githubusercontent.com/34196081/54025534-df1ddc80-41ab-11e9-90f1-95d09d34bf91.png)

**Comment by aalksii** [comment]
Кнопки:
![btns](https://user-images.githubusercontent.com/34196081/54025748-90bd0d80-41ac-11e9-92c6-ddaefd48f056.png)

**Comment by zuevval** [comment]
> Клавиатура:

Хорошо, issue практически выполнен. А в реальных дисплеях тоже такое расположение? А то интуитивно хочется, чтобы клавиши шли по порядку слева направо

**Comment by aalksii** [comment]
За основу была взята реализация с реальных клавиатур Брайля.
К примеру: http://www.nattiq.com/files/braillepen12.bmp

**Comment by zuevval** [comment]
пока остановимся на достигнутом
