### ISSUE TITLE
Приложение "Заметки"

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#64]
- [x] По [Wiki-страничке](https://github.com/zuevval/braille/wiki/Notes-app) проверить, хорошо ли, с вашей точки зрения, Валера описал задачу. Записать в таблицу (Мишину) в common phrases нужные фразы для воспроизведения, отметив "записано" "нет"
- [x] Реализовать приложение
- [x] Тестировать на устройстве (на старом, наверное)

**Comment by mualal** [comment]
Функция braille_to_char, необходимая для приложения Заметки, находится в файле serial_hex.py.

**Comment by zuevval** [comment]
Приложение требует финишной обработки. Наверное, имеет смысл написать для него объяснения, которые будут выводиться по нажатию центра джойстика
