### ISSUE TITLE
Заметки ++

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#78]
- [ ] По нажатию клавиш в главном меню: аппарат произносит вслух вводимые буквы и выводит на ячейку. Если затем 5 секунд бездействия: «Вы ввели текст. Чтобы сохранить как заметку, нажмите вправо. Чтобы продолжить ввод, нажмите вниз, чтобы отменить создание заметки и вернуться в главное меню, нажмите влево»
- [x] Заметки состоят только из текста, без заголовка
- [x] По входу в «Заметки»: «Если Вы хотите создать новую заметку, нажмите вправо. Чтобы пролистать список заметок, нажмите вниз или вверх»
- [x] По пролистыванию вверх-вниз выводятся существующие заметки. По нажатию вправо: «Выберите, что нужно сделать с заметкой. Чтобы удалить, нажмите вниз, (чтобы дополнить, вправо,) чтобы ничего не сделать и вернуться в главное меню - влево» 

Рекомендуется запись аудио с помощью синтезатора Милена
О Милене [Лёша писал вот здесь](https://github.com/zuevval/braille/issues/10#issuecomment-460604652)

**Comment by mualal** [comment]
Сейчас для того, чтобы сохранить заметку, нужно нажать джойстик-вправо. 5 секунд бездействия не реализованы. При вводе в главном меню удалить последний введённый символ можно нажатием джойстик-влево. Чтобы удалить весь введённый текст в главном меню, нужно просто продолжить листать список приложений (джойстик-вниз или джойстик-вверх), затем можно начать вводить новый текст.
