### ISSUE TITLE
Serial в Python

### ISSUE THREAD

**Issue by zuevval** [zuevval/braille#9]
Написать функцию serial_write(var letter), которая принимает на вход символ - букву русского алфавита и отправляет в Serial. Ждёт ответного сигнала (цифра: 1 - успех, 0 - неуспех) и возвращает его. После пяти секунд ожидания при отсутствии сигнала отправляет 0. Назначение - обучающая программа (см. [вики](https://github.com/zuevval/braille/wiki/%D0%9E%D0%B1%D1%83%D1%87%D0%B0%D1%8E%D1%89%D0%B5%D0%B5-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BB%D1%8F-%D1%82%D1%80%D0%B5%D0%BD%D0%B0%D0%B6%D1%91%D1%80%D0%B0-(%D0%BF%D0%BB%D0%B0%D0%BD)))

**Comment by lpvmak** [comment]
Отправлю первую версию, пока не проверял работу с arduino.

**Comment by zuevval** [comment]
> Отправлю первую версию, пока не проверял работу с arduino.

Спасибо!
1. На будущее - просьба не делать commit в master, а создавать из master отдельную ветку
2. Пожалуйста, укажи версию Python

**Comment by zuevval** [comment]
[Вот этот коммит](https://github.com/zuevval/braille/commit/e880404f9e64da307cafccd93d4de94d1267a055) - добавил скетч serial_test.ino и демо использования фунции в python-скрипте. <br>
Проблемы:
1. При вызове serial_close() вылетает с ошибкой - переменная _ser упомянута прежде инициализации (python 3.5)
2. После запуска функция выдаёт (мгновенно) ноль, причём даже если Arduino ничего не пишет в сериал

**Comment by zuevval** [comment]
Решил поменять способ передачи букв (не буквы русского алфавита - будут проблемы с кодировкой - а строки из шести значений ноль/один). В дальнейшем надо, конечно, вмести строчки сделать просто шестнадцатеричное число (с этим почему-то не получилось). Как продолжение этого issue могу предложить переписать мой скоронаписанный код аккуратно, со всеми проверками на то, что Serial открыт или не открыт, как здесь. Пока закрываю issue
